[versions]
guava = "33.4.5-jre"
junit = "4.13.2"
jedis = "5.1.0"
shadow = "9.3.1"
jetbrainsannotations = "26.0.2-1"
minecraft = '1.21.11-R0.1-SNAPSHOT'
velocity = "3.4.0-SNAPSHOT"
worldguard = "7.0.10"
kubernetes = "7.3.1"
mongoDriver = "5.7.0-alpha0"
gson = "2.13.2"
cloud = "2.0.0"
cloudpaper = "2.0.0-beta.10"
fuzzywuzzy = "1.4.0"
influxdb = "7.5.0"
fastboard = "2.1.5"
protobuf-plugin = "0.9.4"
protobuf-java = "4.29.3"
nats = "2.25.1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
junit = { module = "junit:junit", version.ref = "junit" }
jetbrainsannotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsannotations" }
papermc = { module = "io.papermc.paper:paper-api", version.ref = "minecraft" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
kubernetes = { module = "io.fabric8:kubernetes-client", version.ref = "kubernetes" }
mongo = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongoDriver" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
cloud = { module = "org.incendo:cloud-paper", version.ref = "cloudpaper" }
cloudannotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy" }
influxdb = { module = "com.influxdb:influxdb-client-java", version.ref = "influxdb" }
fastboard = { module = "fr.mrmicky:fastboard", version.ref = "fastboard" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf-java" }
nats = { module = "io.nats:jnats", version.ref = "nats" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }

